#!/usr/bin/env node

const { green, red } = require("chalk");
const server = require("./devServer");

const port = process.env.PORT || 8080;
server.listen(port, "0.0.0.0", (err) =>
{
    console.log(
        err ? red(`Unable to start the dev server: ${err.message}`)
            : green(`Dev server is started on ${port}`)
    );
});
